package me.mapacheee.lib.autogenerated_winter_modules.autogenerated_winter_config_module;

import com.google.inject.AbstractModule;
import com.thewinterframework.configurate.module.ConfigurateModule;
import com.thewinterframework.plugin.WinterPlugin;
import com.thewinterframework.plugin.module.PluginModule;
import java.util.List;

public class ConfigurationsModule extends AbstractModule implements PluginModule {
    @Override
    public List<Class<? extends PluginModule>> depends(WinterPlugin plugin) {
        return List.of(ConfigurateModule.class);
    }

    @Override
    protected void configure() {}
}
